asnvbr_homepage:
    path:     /
    defaults: { _controller: AsnvbrBundle:Home:index }

asnvbr_le-club:
    path:     /le-club
    defaults: { _controller: AsnvbrBundle:LeClub:index }
    
asnvbr_nos-formations:
    path:     /nos-formations
    defaults: { _controller: AsnvbrBundle:NosFormations:index }
    
asnvbr_nos-formations/secourisme:
    path:     /nos-formations/secourisme
    defaults: { _controller: AsnvbrBundle:NosFormations:secourisme }
    
asnvbr_nos-formations/secourisme/psc1:
    path:     /nos-formations/secourisme/psc1
    defaults: { _controller: AsnvbrBundle:NosFormations:psc }
     
asnvbr_nos-formations/secourisme/pse1:
    path:     /nos-formations/secourisme/pse1
    defaults: { _controller: AsnvbrBundle:NosFormations:pse1 }
    
asnvbr_nos-formations/secourisme/pse2:
    path:     /nos-formations/secourisme/pse2
    defaults: { _controller: AsnvbrBundle:NosFormations:pse2 }
    
asnvbr_nos-formations/sauvetage:
    path:     /nos-formations/sauvetage
    defaults: { _controller: AsnvbrBundle:NosFormations:sauvetage }
    
asnvbr_nos-formations/sauvetage/bnssa:
    path:     /nos-formations/sauvetage/bnssa
    defaults: { _controller: AsnvbrBundle:NosFormations:bnssa }

asnvbr_nos-formations/sauvetage/bsb:
    path:     /nos-formations/sauvetage/bsb
    defaults: { _controller: AsnvbrBundle:NosFormations:bsb }
    
asnvbr_nos-formations/sauvetage/ens:
    path:     /nos-formations/sauvetage/ens
    defaults: { _controller: AsnvbrBundle:NosFormations:ens }
    
asnvbr_sauvetage-sportif:
    path:     /sauvetage-sportif
    defaults: { _controller: AsnvbrBundle:SauvetageSportif:index }
    
asnvbr_sauvetage-sportif/eau-plate:
    path:     /sauvetage-sportif/eau-plate
    defaults: { _controller: AsnvbrBundle:SauvetageSportif:eauPlate }
    
asnvbr_sauvetage-sportif/cotier:
    path:     /sauvetage-sportif/cotier
    defaults: { _controller: AsnvbrBundle:SauvetageSportif:cotier }
    
asnvbr_le-coin-des-licencies/le-poste-de-secours:
    path:     /le-coin-des-licencies/le-poste-de-secours
    defaults: { _controller: AsnvbrBundle:CoinLicencies:posteSecours }
    
asnvbr_contact:
    path:     /contact
    defaults: { _controller: AsnvbrBundle:Contact:index }